### ISSUE TITLE
[SIDE-FILTER] - Problema com a propriedade on-filter

### ISSUE THREAD

**Issue by ThiagoRossetto** [eitsopensource/eits-md#25]
A propriedade "on-filter" está sendo executada mesmo sem a realização de nenhuma ação. Logo, ao carregar o template que a possui, será executado o método referenciado dentro da mesma.

Forma de utilização:
`<side-filter filters="model.filters" title="Filtros" on-filter="changeToList(false)">`

Na forma de utilização descrita acima, o método "changeToList" será chamado duas vezes no carregamento da página. O primeiro carregamento é realizado pela própria renderização da página (comportamento esperado, portando, correto), e a segunda é pelo próprio "on-filter".

**Comment by muchael** [comment]
> Na forma de utilização descrita acima, o método "changeToList" será chamado duas vezes no carregamento da página. O primeiro carregamento é realizado pela própria renderização da página (comportamento esperado, portando, correto), e a segunda é pelo próprio "on-filter".

**Comment by muchael** [comment]
> fdsf <ytasadsad>

**Comment by muchael** [comment]
> teste `<td>`
