### ISSUE TITLE
[PAPER-SHEET] - O componente paper-sheet está 'escutando' todos os eventos de clique, inclusive os cliques das modais sobrepostas.

### ISSUE THREAD

**Issue by emanuelvictor** [eitsopensource/eits-md#30]
A sugestão é fazer com que o componente escute somente os cliques sobre si mesmo, da mesma forma que é no admin do google.

**Comment by ealves** [comment]
Corrigido.

https://github.com/ealves/eits-md/commit/0d7c85ff827247cb3c08648ef5b167ff4

**Comment by emanuelvictor** [comment]
Bug corrigido, ok.
